<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Migration for TYPO3.Release
 */
class Version20111019194531 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE typo3_release_domain_model_downloadformat (flow3_persistence_identifier VARCHAR(40) NOT NULL, download VARCHAR(40) DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, sha1 VARCHAR(255) DEFAULT NULL, INDEX IDX_D2ABF22E781A8270 (download), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_release_domain_model_downloadformat ADD CONSTRAINT FK_D2ABF22E781A8270 FOREIGN KEY (download) REFERENCES typo3_release_domain_model_download(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_release_domain_model_download ADD xrelease VARCHAR(40) DEFAULT NULL, ADD label VARCHAR(255) DEFAULT NULL, DROP filename, DROP url, DROP sha1");
		$this->addSql("ALTER TABLE typo3_release_domain_model_download ADD CONSTRAINT FK_CC608AA29E47031D FOREIGN KEY (xrelease) REFERENCES typo3_release_domain_model_release(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_CC608AA29E47031D ON typo3_release_domain_model_download (xrelease)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE typo3_release_domain_model_downloadformat");
		$this->addSql("ALTER TABLE typo3_release_domain_model_download DROP FOREIGN KEY FK_CC608AA29E47031D");
		$this->addSql("DROP INDEX IDX_CC608AA29E47031D ON typo3_release_domain_model_download");
		$this->addSql("ALTER TABLE typo3_release_domain_model_download DROP xrelease, CHANGE label sha1 VARCHAR(255) DEFAULT NULL");
	}
}

?>