<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * 0-Migration for TYPO3.Relase
 */
class Version20111019172718 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE typo3_release_domain_model_download (flow3_persistence_identifier VARCHAR(40) NOT NULL, filename VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, sha1 VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_release_domain_model_releasenotes (flow3_persistence_identifier VARCHAR(40) NOT NULL, teaser VARCHAR(255) DEFAULT NULL, article VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_release_domain_model_release (flow3_persistence_identifier VARCHAR(40) NOT NULL, branch VARCHAR(40) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, date DATETIME DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, INDEX IDX_EFF1E6E1BB861B1F (branch), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_release_domain_model_product (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_release_domain_model_branch (flow3_persistence_identifier VARCHAR(40) NOT NULL, product VARCHAR(40) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, phpversions VARCHAR(255) DEFAULT NULL, mysqlversions VARCHAR(255) DEFAULT NULL, giturl VARCHAR(255) DEFAULT NULL, INDEX IDX_BCE66E5BD34A04AD (product), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_release_domain_model_release ADD CONSTRAINT FK_EFF1E6E1BB861B1F FOREIGN KEY (branch) REFERENCES typo3_release_domain_model_branch(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_release_domain_model_branch ADD CONSTRAINT FK_BCE66E5BD34A04AD FOREIGN KEY (product) REFERENCES typo3_release_domain_model_product(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_release_domain_model_branch DROP FOREIGN KEY FK_BCE66E5BD34A04AD");
		$this->addSql("ALTER TABLE typo3_release_domain_model_release DROP FOREIGN KEY FK_EFF1E6E1BB861B1F");
		$this->addSql("DROP TABLE typo3_release_domain_model_download");
		$this->addSql("DROP TABLE typo3_release_domain_model_releasenotes");
		$this->addSql("DROP TABLE typo3_release_domain_model_release");
		$this->addSql("DROP TABLE typo3_release_domain_model_product");
		$this->addSql("DROP TABLE typo3_release_domain_model_branch");
	}
}

?>